### ISSUE TITLE
Feature Request:  Add Search by X-Keyword (Tags)

### ISSUE THREAD

**Issue by snuffop** [panjie/mu4e-goodies#1]
Hey  Love the work,  I really like the tags addon to the goodies.  I would like to be able to search by the tags added.   As I'm a Lisp super Noob, do you have any pointers on how to do this >?

**Comment by panjie** [comment]
Hello, you can search like this:
1. Type `s` into the search
2. Input `tag:XXX`

**Comment by snuffop** [comment]
Well that's too easy.  thanks.
